openapi: 3.0.3
info:
  title: moncycle.app
  description: API to access data of moncycle.app, an open-source app for natural methods of tracking menstrual cycle
  version: 0.0.1
#servers:
#  - url: https://tableau.moncycle.app/api
paths: 
  "/api/pub_stat":
    get:
      summary: statistiques publique
      description: "Permet de récuperrer les données publiques d'utilisation de moncycle.app"
      responses:
        200:
          description: "les données au format JSON"
  "/api/authentication":
    get:
      summary: obtenir un jetton d'auth
      description: "permet de récuperrer un jetton (token) d'authentification afin d'utiliser l'API"
      reponses:
        200:
          description: "auth OK"
